### ISSUE TITLE
Keep activity running over screenlock

### ISSUE THREAD

**Issue by pando85** [de-live-gdev/cherrymusic_android#2]
Hello! this application is simple and usefull but I have a problem when my screen is lock.
I've never program something for android but I found this: https://stackoverflow.com/questions/11545865/keep-activity-running-over-screen-lock-when-the-screens-alseep
Thanks for this app!

**Comment by de-live-gdev** [comment]
Can you describe your problem a little closer? What does happen?   
Does playback stop?  

I just found one bug which keeps asking "Confirm Navigation" after getting back to app again -> This will be fixed in next release

**Comment by pando85** [comment]
Yes, first appears "Confirm Navigation" and if you wait the next song is not playing.

**Comment by de-live-gdev** [comment]
Below is a test version of the next version, please try it, and tell me if it fixes your problem.You will maybe need to uninstall the app from your device before installing this one (depends on from where you did get your Cherry).  

Please let me know if it works, or if there are still problems.  

[cherry_debug.apk.zip](https://github.com/de-live-gdev/cherrymusic_android/files/60674/cherry_debug.apk.zip)
Note: GitHub Issues only allow .zip files for upload ;)

**Comment by pando85** [comment]
Thank you very much, I was learning some Java and I have a work around but I we will need to discuss it probably because I'm very noob with this.

I will try your new version and I will comment it here.

**Comment by de-live-gdev** [comment]
No problem, nobody starts as an expert. ;).  
You can also contact me using other services, just take a look at <http://de-live-gdev.github.io/> on the left side. GH Issues are not that great for discussion :D

**Comment by pando85** [comment]
Ok, finally I discover that I was wrong... sorry. 
The bug is not related with stop playing music when device is lock.
The problem is related with flac files. Seekbar doesn't work (https://github.com/devsnd/cherrymusic/issues/275) and, in this app, the time doesn't start count while the song is playing and when the song finish the next one never start (with or without locked device). I think it could be a problem with WebView and not with your code.

**Comment by gsantner** [comment]
@pando85 
If you are still using the app: I update the app, replaced most stuff. The update should be out soon on F-Droid.
