### ISSUE TITLE
failed to load file browser

### ISSUE THREAD

**Issue by kwhitefoot** [de-live-gdev/cherrymusic_android#3]
When I click the browse files button I receive a message saying "failed to load file browser".  This happens on local host and when connecting from a remote device (Android tablet).

**Comment by de-live-gdev** [comment]
Hi @kwhitefoot,
this seems to be an issue with you cherrymusic installation, please head over to cherrymusic project page, or the issue tracker.  

Here are some links that maybe are helpful: 
<http://www.fomori.org/cherrymusic/Setup%20Guide.html>
<http://www.fomori.org/cherrymusic/FAQ.html>
<https://github.com/devsnd/cherrymusic/issues>

**Comment by gsantner** [comment]
@kwhitefoot 
If you are still using the app: I update the app, replaced most stuff. The update should be out soon on F-Droid.
